spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/barber-shop-db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    remote:
      secret: 123
    restart:
      trigger-file: trigger.txt